
//! Autogenerated weights for pallet_template
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ../../target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_template
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/template/src/weights.rs
// --template
// ../../.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_template.
pub trait WeightInfo {
	fn transfer() -> Weight;
	fn transfer_from() -> Weight;
	fn approve() -> Weight;
	fn mint() -> Weight;
	fn burn() -> Weight;
	fn increase_allowance() -> Weight;
	fn decrease_allowance() -> Weight;
}

/// Weights for pallet_template using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn approve() -> Weight {
		Weight::from_parts(8_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn transfer() -> Weight {
		Weight::from_parts(8_000_000, 0).saturating_add(T::DbWeight::get().writes(1_u64))
	}

	fn transfer_from() -> Weight {
		Weight::from_parts(12_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	fn burn() -> Weight {
		Weight::from_parts(11_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn mint() -> Weight {
		Weight::from_parts(11_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn increase_allowance() -> Weight {
		Weight::from_parts(10_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn decrease_allowance() -> Weight {
		Weight::from_parts(10_000_000, 0).saturating_add(RocksDbWeight::get().writes(1_u64))
	}


}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn approve() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}
	fn transfer() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}

	fn transfer_from() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}

	fn mint() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}

	fn burn() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}

	fn increase_allowance() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}
	fn decrease_allowance() -> Weight {
		Weight::from_parts(9_000_000, 0)
	}
}
